server:
  port: 3406

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 观察是否需要加时区
    username: root
    password: yyb161119
    driver-class-name: com.mysql.cj.jdbc.Driver

    # mysql8 needs timezone application
